SWIDEA_SITE/server/apps/posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
  path('', views.post_list, name='list'),
  path('post/<int:pk>/', views.post_detail, name='detail'),
  path('post/create/', views.PostCreate.as_view(), name='create'),
  path('post/update/<int:pk>/', views.PostUpdate.as_view(), name='update'),
  path('post/delete/<int:pk>/', views.post_delete, name='delete'),
  path('tool/', views.tool_list, name='tool_list'),
  path('tool/<int:pk>/', views.tool_detail, name='tool_detail'),
  path('tool/create/', views.ToolCreate.as_view(), name='tool_create'),
  path('tool/update/<int:pk>/', views.ToolUpdate.as_view(), name='tool_update'),
  path('tool/delete/<int:pk>/', views.tool_delete, name='tool_delete'),
  path('post/like/<int:post_pk>/', views.likes, name='likes'),
]

SWIDEA_SITE/server/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('server.apps.posts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

SWIDEA_SITE/server/apps/posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
# from wagtail.wagtailadmin.edit_handlers import FieldPanel, MultiFieldPanel

# Create your models here.

class Tool(models.Model):
  name = models.CharField(max_length=30, verbose_name= '이름')
  kind = models.CharField(max_length=30, verbose_name= '종류')
  content = models.TextField(verbose_name= '개발툴 설명')

  def __str__(self):
    return self.name
    
  def get_absolute_url(self):
    return f'/tool/{self.pk}/'
  

class Post(models.Model):
  user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
  like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles', null=True)
  title = models.CharField(max_length=30, verbose_name= '아이디어명')
  image = models.ImageField(upload_to="posts/%Y%m%d", verbose_name='Image')
  content = models.TextField(verbose_name='아이디어 설명')
  interest = models.IntegerField(default=0,verbose_name='아이디어 관심도')
  devtool = models.ForeignKey(Tool, null=True, on_delete=models.SET_NULL, related_name="post_user",verbose_name='예상 개발툴')
  
  # custom_panels = [
  #           MultiFieldPanel([
  #               FieldRowPanel([
  #                   FieldPanel('first_name', classname='fn'),
  #                   FieldPanel('last_name', classname='ln'),
  #               ]),
  #               FieldPanel('address', classname='custom1',)
  #           ])
  #       ]
  # edit_handler = ObjectList(custom_panels)

  def __str__(self):
    return self.title
  
  def get_absolute_url(self):
    return f'/post/{self.pk}/'
  
  def total_likes(self):
    return self.likes.count()

SWIDEA_SITE/server/apps/posts/views.py
from django.shortcuts import render, redirect
from .models import Post, Tool
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import get_object_or_404
from django.http import HttpResponse,JsonResponse
import json

# Create your views here.

def post_list(request):  
  sort = request.GET.get('sort','')
  if sort == 'pk':
    post_li = Post.objects.all().order_by("pk")
  elif sort == 'title':
    post_li = Post.objects.all().order_by("title")
  elif sort == 'new':
    post_li = Post.objects.all().order_by("-pk")
  elif sort == 'like':
    post_li = Post.objects.all().order_by("like_users")
  else:
    post_li = Post.objects.all()
    
  page = request.GET.get('page', 1)
  paginator = Paginator(post_li, 4)
  
  try:
    posts = paginator.page(page)
  except PageNotAnInteger:
    posts = paginator.page(1)
  except EmptyPage:
    posts = paginator.page(paginator.num_pages)

  context = {
    "posts" : posts,
  }
  return render(request, 'posts/post_list.html', context=context)

def post_detail(request, pk):
  post = Post.objects.get(pk=pk)
  tool_pk = post.devtool.pk
  context = {
    "post" : post,
    "tool_pk" : tool_pk,
  }
  return render(request, 'posts/post_detail.html', context=context)

def tool_list(request):
  tool_li = Tool.objects.all()
  page = request.GET.get('page', 1)
  paginator = Paginator(tool_li, 6)
  try:
    tools = paginator.page(page)
  except PageNotAnInteger:
    tools = paginator.page(1)
  except EmptyPage:
    tools = paginator.page(paginator.num_pages)
  context = {
    "tools" : tools,
  }
  return render(request, 'posts/tool_list.html', context=context)

def tool_detail(request, pk):
  tool = Tool.objects.get(pk=pk)
  post = Post.objects.all()
  tool_posts = Post.objects.filter(devtool=tool.id)
  context = {
    "tool" : tool,
    "tool_posts" : tool_posts,
  }
  return render(request, 'posts/tool_detail.html', context=context)

# def post_create(request, *args, **kwargs):
#   if request.method == "POST":
#     Post.objects.create(
#       title=request.POST["title"],
#       image=request.FILES["image"],
#       content=request.POST["content"],
#       interest=request.POST["interest"],
#       devtool=request.POST["devtool"],
#     )
#     return redirect("/")
#   return render(request, "posts/post_create.html")

class PostCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
  model = Post
  fields = ['title', 'image', 'content', 'interest', 'devtool']
  template_name = 'posts/post_create.html'

  def test_func(self):
    return self.request.user.is_superuser or self.request.user.is_staff

  def form_valid(self, form):
    current_user = self.request.user

    if current_user.is_authenticated and (current_user.is_superuser or current_user.is_staff):
      return super(PostCreate, self).form_valid(form)
    else:
      return redirect('/')
  
class PostUpdate(LoginRequiredMixin, UpdateView):
  model = Post
  fields = ['title', 'image', 'content', 'interest', 'devtool']

  template_name = 'posts/post_update.html'

  def dispatch(self, request, *args, **kwargs):
    return super(PostUpdate, self).dispatch(request, *args, **kwargs)

def post_delete(request, pk):
  login_session = request.session.get('login_session', '')
  post = get_object_or_404(Post, id=pk)
  post.delete()
  return redirect('/')

class ToolCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
  model = Tool
  fields = ['name', 'kind', 'content']
  template_name = 'posts/tool_create.html'

  def test_func(self):
    return self.request.user.is_superuser or self.request.user.is_staff

  def form_valid(self, form):
    current_user = self.request.user

    if current_user.is_authenticated and (current_user.is_superuser or current_user.is_staff):
      return super(ToolCreate, self).form_valid(form)
    else:
      return redirect('/tool/')
    
class ToolUpdate(LoginRequiredMixin, UpdateView):
  model = Tool
  fields = ['name', 'kind', 'content']

  template_name = 'posts/tool_update.html'

  def dispatch(self, request, *args, **kwargs):
    return super(ToolUpdate, self).dispatch(request, *args, **kwargs)

def tool_delete(request, pk):
  login_session = request.session.get('login_session', '')
  tool = get_object_or_404(Tool, id=pk)
  tool.delete()
  return redirect('/tool/')

def post_like(request, post_id):
  response_body = {"result": ""}

  if request.user.is_authenticated:
    if request.method == "POST":
      post = get_object_or_404(Post, pk=post_id)
      existed_user = post.likes.filter(pk=request.user.id).exists()

      if existed_user:
        post.likes.remove(request.user)
        response_body["result"] = "dislike"

      else:
        post.likes.add(request.user)
        response_body["result"] = "like"

      post.save()
      return JsonResponse(status=200, data=response_body)

  else:
      return JsonResponse(status=403, data=response_body)

def likes(request, post_pk):
  if request.user.is_authenticated:
    post = get_object_or_404(Post, pk=post_pk)

    if post.like_users.filter(pk=request.user.pk).exists():
        post.like_users.remove(request.user)
    else:
        post.like_users.add(request.user)
    return redirect('posts:list')
  return redirect('/')

# def like_post(request, pk):
  # if request.is_ajax(): #ajax 방식일 때 아래 코드 실행
  #   blog_id = request.GET['post.pk'] #좋아요를 누른 게시물id (blog_id)가지고 오기
  #   post = Blogapp.objects.get(id=blog_id) 
    
  #   if not request.user.is_authenticated: #버튼을 누른 유저가 비로그인 유저일 때
  #       message = "로그인을 해주세요" #화면에 띄울 메세지 
  #       context = {'like_count' : post.like.count(),"message":message}
  #       return HttpResponse(json.dumps(context), content_type='application/json')

  #   user = request.user #request.user : 현재 로그인한 유저
  #   if post.like.filter(id = user.id).exists(): #이미 좋아요를 누른 유저일 때
  #       post.like.remove(user) #like field에 현재 유저 추가
  #       message = "좋아요 취소" #화면에 띄울 메세지
  #   else: #좋아요를 누르지 않은 유저일 때
  #       post.like.add(user) #like field에 현재 유저 삭제
  #       message = "좋아요" #화면에 띄울 메세지
  #   context = {'like_count' : post.like.count(),"message":message}
    
  #   return HttpResponse(json.dumps(context), content_type='application/json')   
  

SWIDEA_SITE/server/apps/posts/templates/posts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>SW_IDEA</title>
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://kit.fontawesome.com/f95b2ab384.js" crossorigin="anonymous"></script>
</head>
<body>
  <header class="d-flex justify-content-around py-3">
    <a href="{% url 'posts:list' %}">My <span id="color-ch">SW Idea</span> Manage</a>
    <div class="d-flex justify-content-between nav-con">
      <a href="{% url 'posts:create' %}">아이디어 등록</a>
      <a href="{% url 'posts:list' %}">아이디어 관리</a>
      <a href="{% url 'posts:tool_create' %}">개발툴 등록</a>
      <a href="{% url 'posts:tool_list' %}">개발툴 관리</a>
    </div>
  </header>
  <div class="container my-5 p-4" id="main-con">
    {% block content %}
    {% endblock %}
  </div>
  <footer>

  </footer>
  <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
  <script type="text/javascript" src="{% static 'js/post.js' %}"></script>
  {% comment %} <script type="text/javascript">
    function post_like(id) {
      $.ajax({
          url: "{% url 'posts:like_post' %}", // data를 전송할 url 입니다.
          data: {
              'post.pk': id
          }, // post_id 라는 name으로 id 값 전송
          dataType: "json",
          success: function (response) { // ajax 통신이 정상적으로 완료되었을 때
              $('#like_count').html(response.like_count) //id가 like_count의 내용을 전송받은 좋아요 수로 바꾼다
              $('#message').html(response.message) //id가 message의 내용을 전송받은 message로 바꾼다
              $('.toast').fadeIn(400).delay(100).fadeOut(400)
              if (response.message == "좋아요")
              //좋아요 눌렀을 때 
              {
                  $('#heart').attr("class", "fas fa-heart")
              } else if (response.message == "좋아요 취소")
              //좋아요 상태에서 다시 눌렀을 때 
              {
                  $('#heart').attr("class", "far fa-heart")
              }
          }
      })
    }
  </script> {% endcomment %}
</body>
</html>

SWIDEA_SITE/server/apps/posts/templates/posts/post_create.html
{% extends 'posts/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="text-center">
    <h2>Idea Register</h2>
    <p>아이디어 등록 페이지 입니다. 당신의 아이디어를 잊지 말고 기록하세요!</p>
  </div>
  <div class="container d-flex justify-content-center">
    <!-- <form action="{% url 'posts:create' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <p class="text-light">아이디어명:</p>
      <input name="title" />
      <br />
      <p class="text-light">Image:</p>
      <input type="file" name="image">
      <br />
      <p class="text-light">아이디어 설명:</p>
      <textarea name="content"></textarea>
      <br />
      <p class="text-light">아이디어 관심도:</p>
      <input name="interest" type="number"/>
      <br />
      <p class="text-light">예상 개발툴:</p>
      <input name="devtool" />
      <br />
      <div>
        <input type="submit" , value="SUBMIT" />
      </div>
    </form> -->
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <table>
        {{form | crispy}}
        {{form.media}}
      </table>
      <div class="d-flex justify-content-center">
        <button type="submit" class="btn btn-light m-2">SUBMIT</button>
      </div>
    </form>
    </div>
{% endblock %}

SWIDEA_SITE/server/apps/posts/templates/posts/post_detail.html
{% extends 'posts/base.html' %}

{% block content %}
  <div class="text-center">
    <h2>Idea Detail</h2>
    <p>아이디어 세부내용 페이지 입니다. 당신이 구현하려 한 아이디어들을 자세히 살펴보세요.</p>
  </div>
  <div class="d-flex align-items-center" id="detail-main">
    <img src="{{post.image.url}}" height="250rem" width="350rem" alt="" class="p-3" />
    <div class="ms-4">
      <h3 class="font-weight-bold">{{post.title}}
        {% if user in post.like_users.all %}
          <button class="btn btn-link text-danger disabled">
            <i class="fa fa-heart fa-2x"></i>
          </button>
        {% else %}
          <button class="btn btn-link text-danger disabled">
            <i class="fa fa-heart-o fa-2x"></i>
          </button>
        {% endif %}
      </h3>
      <br>
      <p>1) 아이디어 관심도</p>
      <p>{{post.interest}}</p>
      <p>2) 예상 개발 툴</p>
      <p class="p_detail"><a href="{% url 'posts:tool_detail' tool_pk %}">{{post.devtool}}</a></p>
      <p>3) 아이디어 설명</p>
      <p>{{post.content}}</p>
    </div>
  </div>
  <div class="d-flex justify-content-center m-4">
    <a href="{% url 'posts:delete' post.pk %}" role="button" class="btn btn-sm btn-danger mx-4">삭제</a>
    <a href="{% url 'posts:list' %}" role="button" class="btn btn-sm btn-light mx-4">목록</a>
    <a href="{% url 'posts:update' post.pk %}" role="button" class="btn btn-sm btn-primary mx-4">수정</a>
  </div>
{% endblock %}

SWIDEA_SITE/server/apps/posts/templates/posts/post_list.html
{% extends 'posts/base.html' %}

{% block content %}
  <div class="text-center">
    <h2>Idea List</h2>
    <p>나의 아이디어를 잊지 말고 기록해보세요</p>
  </div>
  <form action="/" method="get" id="sort" class="d-flex justify-content-end me-5 mb-2">
    <select onchange="location = this.value;" id="selectbox">
      <option class="sort-pk" value="/">--정렬기준--</option>
      <option class="sort-pk" value="?sort=pk">등록순</option>
      <option class="sort-title" value="?sort=title">이름순</option>
      <option class="sort-new" value="?sort=new">최신순</option>
      <option class="sort-like" value="?sort=like">찜하기순</option>
    </select>
  </form>
  <div id="postlist_main" class="row">
    {% for post in posts %}
    <div class="col-3">
      <div class="card m-3 card-bg">
        <img class="card-img-top p-4" src="{{post.image.url}}" alt="{{post}}의 img" height="270rem" width="270rem">
        <form action="{% url 'posts:likes' post.pk %}" method='POST'>
          {% csrf_token %}
          {% if user in post.like_users.all %}
            <button class="btn btn-link text-danger heart-btn">
              <i class="fa fa-heart fa-2x"></i>
            </button>
          {% else %}
            <button class="btn btn-link text-danger heart-btn">
              <i class="fa fa-heart-o fa-2x"></i>
            </button>
          {% endif %}
        </form>
        <div class="card-body">
          <a href="{% url 'posts:detail' post.pk %}">{{post.title}}</a>
          <hr />
          <p>예상 개발 툴: {{post.devtool}}</p>
          <p>아이디어 관심도: 
            <form action="{% url 'posts:list' %}" method="POST">
              {% csrf_token %}
              <input type="submit" value=" - " class="btn btn-sm">
              <span id="input-{{post.pk}}">{{post.interest}}</span>
              <input type="submit" value=" + " class="btn btn-sm">
            </form>
          </p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  <div class="d-flex justify-content-center mt-3">
    {% if posts.has_other_pages %}
      <ul class="pagination">
        {% if posts.has_previous %}
          <li><a class="btn btn-sm" href="?page={{ posts.previous_page_number }}">&lt;</a></li>
        {% else %}
          <li class="disabled btn btn-sm"><span>&lt;</span></li>
        {% endif %}
        {% for i in posts.paginator.page_range %}
          {% if posts.number == i %}
            <li class="active bg-light btn btn-sm"><span>{{ i }}</span></li>
          {% else %}
            <li><a class="btn btn-sm" href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}
        {% if posts.has_next %}
          <li><a class="btn btn-sm" href="?page={{ posts.next_page_number }}">&gt;</a></li>
        {% else %}
          <li class="disabled btn btn-sm"><span>&gt;</span></li>
        {% endif %}
      </ul>
    {% endif %}
  </div>
{% endblock %}

SWIDEA_SITE/server/apps/posts/templates/posts/post_update.html
{% extends 'posts/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="text-center">
    <h2>Idea Deatil Update</h2>
    <p>아이디어 세부내용 수정 페이지 입니다. 아이디어를 구체화하거나 내용을 변경해 보아요.</p>
  </div>
  <div class="container d-flex justify-content-center">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <table>
        {{form | crispy}}
        {{form.media}}
      </table>
      <div class="d-flex justify-content-center">
        <button type="submit" class="btn btn-light m-2">SUBMIT</button>
      </div>
    </form>
    </div>
{% endblock %}

SWIDEA_SITE/server/apps/posts/templates/posts/tool_create.html
{% extends 'posts/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="text-center">
    <h2>Tool Register</h2>
    <p>개발툴 등록 페이지 입니다. 당신의 아이디어를 잊지 말고 기록하세요!</p>
  </div>
  <div class="container d-flex justify-content-center">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <table>
        {{form | crispy}}
        {{form.media}}
      </table>
      <div class="d-flex justify-content-center">
        <button type="submit" class="btn btn-light m-2">SUBMIT</button>
      </div>
    </form>
    </div>
{% endblock %}

SWIDEA_SITE/server/apps/posts/templates/posts/tool_detail.html
{% extends 'posts/base.html' %}

{% block content %}
  <div class="text-center">
    <h2>DevTool Detail</h2>
    <p>개발툴 세부내용 페이지 입니다. 자신이 다룰 수 있는 개발툴에 대한 상세내용을 확인해 보아요.</p>
  </div>
  <div id="detail-main">
    <h2 class="font-weight-bold mt-3 mb-4 color-tool">{{tool.name}}</h2>
    <p>{{tool.kind}}
      <br>{{tool.content}}
    </p>
    <hr id="toolde-hr">
    <p class="font-weight-bold color-tool">>만들 수 있는 SW 목록</p>
    {% for post in tool_posts %}
      <p><a href="{% url 'posts:detail' post.pk %}">{{post.title}}</a></p>
    {% endfor %}
  </div>
  <div class="d-flex justify-content-center m-4">
    <a href="{% url 'posts:tool_delete' tool.pk %}" role="button" class="btn btn-sm btn-danger mx-4">삭제</a>
    <a href="{% url 'posts:tool_list' %}" role="button" class="btn btn-sm btn-light mx-4">목록</a>
    <a href="{% url 'posts:tool_update' tool.pk %}" role="button" class="btn btn-sm btn-primary mx-4">수정</a>
  </div>
{% endblock %}

SWIDEA_SITE/server/apps/posts/templates/posts/tool_list.html
{% extends 'posts/base.html' %}

{% block content %}
  <div class="text-center mb-5">
    <h2>DevTool List</h2>
    <p>개발툴 목록 페이지 입니다. 자신이 사용가능한 개발들의 목록을 확인해 보세요.</p>
  </div>
  <hr id="tool-hr" />
  {% for tool in tools %}
  <div class="row text-center" id="toolli-content">
    <div class="col-2">
      <a href="{% url 'posts:tool_detail' tool.pk %}" class="text-dark font-weight-bold">{{tool.name}}</a>
    </div>
    <div class="col-3">
      <p class="font-weight-bold">{{tool.kind}}</p>
    </div>
    <div class="col-7">
      <p class="text-dark">{{tool.content | truncatechars:40}}</p>
    </div>
  </div>
  {% endfor %}
  <div class="d-flex justify-content-center mt-5">
    {% if tools.has_other_pages %}
      <ul class="pagination">
        {% if tools.has_previous %}
          <li><a class="btn btn-sm" href="?page={{ tools.previous_page_number }}">&lt;</a></li>
        {% else %}
          <li class="disabled btn btn-sm"><span>&lt;</span></li>
        {% endif %}
        {% for i in tools.paginator.page_range %}
          {% if tools.number == i %}
            <li class="active bg-light btn btn-sm"><span>{{ i }}</span></li>
          {% else %}
            <li><a class="btn btn-sm" href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}
        {% if tools.has_next %}
          <li><a class="btn btn-sm" href="?page={{ tools.next_page_number }}">&gt;</a></li>
        {% else %}
          <li class="disabled btn btn-sm"><span>&gt;</span></li>
        {% endif %}
      </ul>
    {% endif %}
  </div>
{% endblock %}

SWIDEA_SITE/server/apps/posts/templates/posts/tool_update.html
{% extends 'posts/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="text-center">
    <h2>Idea Deatil Update</h2>
    <p>아이디어 세부내용 수정 페이지 입니다. 아이디어를 구체화하거나 내용을 변경해 보아요.</p>
  </div>
  <div class="container d-flex justify-content-center">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <table>
        {{form | crispy}}
        {{form.media}}
      </table>
      <div class="d-flex justify-content-center">
        <button type="submit" class="btn btn-light m-2">SUBMIT</button>
      </div>
    </form>
    </div>
{% endblock %}